config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
	path("", include("finance.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("allauth.urls")),
]

finance/urls.py
from django.urls import path

from finance.views import index, transactions_list


app_name="finance"

urlpatterns = [
	path("", index, name="index"),
	path("transactions/", transactions_list, name="transactions_list"),
]

finance/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
	pass


class Category(models.Model):
	name = models.CharField(max_length=50, unique=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		verbose_name_plural = "Categories"

	def __str__(self):
		return self.name


class Transaction(models.Model):
	TRANSACTION_TYPE_CHOICES = (
		("i", "Income"),
		("e", "Expense"),
	)

	user = models.ForeignKey(User, on_delete=models.CASCADE)
	category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, blank=True, null=True)
	type = models.CharField(max_length=1, choices=TRANSACTION_TYPE_CHOICES)
	amount = models.DecimalField(max_digits=10, decimal_places=2)
	date = models.DateTimeField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return f"{self.type} of {self.amount} on {self.date} by {self.user}"

	class Meta:
		ordering = ["-date"]

finance/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from finance.filters import TransactionFilter
from finance.models import Transaction


def index(request):
    return render(request, "finance/index.html")


@login_required
def transactions_list(request):
    transaction_filter = TransactionFilter(
        request.GET,
        queryset=Transaction.objects.filter(user=request.user).select_related("category")
    )
    
    context = {
        "transaction_filter":transaction_filter
    }

    if request.htmx:
        return render(request, "finance/partials/transactions_container.html", context)

    return render(request, "finance/transactions_list.html", context)

finance/templates/finance/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block head_title %}
            Apex Finance
        {% endblock head_title %}
    </title>


    <!-- HTMX -->
    <script src="{% static 'js/htmx.min.js' %}" defer></script>
    
    <!-- DaisyUI and TailwindCSS -->
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.10/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com?plugins=typography"></script>

    <!-- Custom files -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />


    {% block extra_head %}

    {% endblock %}
</head>
<body>

    {% include 'finance/partials/navbar.html' %}

    <div class="max-w-screen-lg mx-auto p-4">

        {% block content %}
        {% endblock %}
    </div>

    
</body>
</html>

finance/templates/finance/index.html
{% extends 'finance/base.html' %}


{% block content %}

<h1 class="mt-4 mb-6 text-2xl leading-none tracking-tight text-white md:text-3xl lg:text-4xl">
    Welcome to the Personal Finance Tracker
</h1>


{% if user.is_authenticated %}

    <div class="flex items-center mb-6">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="mr-2 w-6 h-6 text-white">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.182 15.182a4.5 4.5 0 01-6.364 0M21 12a9 9 0 11-18 0 9 9 0 0118 0zM9.75 9.75c0 .414-.168.75-.375.75S9 10.164 9 9.75 9.168 9 9.375 9s.375.336.375.75zm-.375 0h.008v.015h-.008V9.75zm5.625 0c0 .414-.168.75-.375.75s-.375-.336-.375-.75.168-.75.375-.75.375.336.375.75zm-.375 0h.008v.015h-.008V9.75z" />
        </svg>
    
        <p class="text-xl text-white">
            Welcome, {{ user.username }}
        </p>
    </div>
    <div class="border mb-6"></div>
    <div class="mb-3">
        <a 
            href="{% url 'finance:transactions_list' %}" 
            class="font-medium text-white hover:underline flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 me-2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 0 1 3 19.875v-6.75ZM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V8.625ZM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V4.125Z" />
            </svg>
              
            View My Transacitons
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 ml-1">
                <path stroke-linecap="round" stroke-linejoin="round" d="M17.25 8.25 21 12m0 0-3.75 3.75M21 12H3" />
            </svg>
              
              
        </a>
    </div>

{% else %}

{% endif %}


<p class="text-white">{% lorem %}</p>

{% endblock content %}

finance/templates/finance/partials/navbar.html
{% load static %}
<nav>
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
      <a href="{% url 'finance:index' %}" class="flex items-center">
        <span class="self-center text-2xl font-semibold whitespace-nowrap">Apex Finance</span>
      </a>
      <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
      </button>
      <div class="hidden w-full md:block md:w-auto" id="navbar-default">
        <ul class="font-medium flex flex-col p-4 md:p-0 my-1 md:my-2 rounded-lg md:flex-row md:space-x-8">
        
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'finance:transactions_list' %}" 
                    class="block py-2 pl-3 pr-4 text-white rounded md:p-0" 
                    aria-current="page">
                        My Transactions
                </a>
            </li>
            <li>
                <a href="{% url 'account_logout' %}" 
                    class="block py-2 pl-3 pr-4 text-white rounded md:p-0" 
                    aria-current="page">
                        Logout
                </a>
            </li>
        {% else %}
            <li>
                <a href="{% url 'account_login' %}" 
                    class="block py-2 pl-3 pr-4 text-white rounded md:p-0" 
                    aria-current="page">
                        Login
                </a>
            </li>
            <li>
                <a href="{% url 'account_signup' %}" 
                    class="block py-2 pl-3 pr-4 text-white rounded md:p-0" 
                    aria-current="page">
                        Sign Up
                </a>
            </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  

finance/templates/finance/partials/transactions_container.html
{% load widget_tweaks %}

<!-- Grid container div -->
<div class="flex flex-col-reverse md:grid md:grid-cols-4 md:gap-4" id="transaction_container">
	<!-- 3/4 of cols for transaction table -->
	<div class="col-span-3">
		{% if transaction_filter.qs %}

			<table class="table ">
				<thead class="text-xs text-white uppercase">
					<tr>
						<th class="px-6 py-3">Date</th>
						<th class="px-6 py-3">Category</th>
						<th class="px-6 py-3">Type</th>
						<th class="px-6 py-3">Amount</th>
					</tr>
				</thead>
				<tbody>
					
					{% for transaction in transaction_filter.qs %}

						<tr>
							<td class="px-6 py-3">{{ transaction.date }}</td>
							<td class="px-6 py-3">{{ transaction.category }}</td>
							<td class="px-6 py-3">

								{% if transaction.type == 'i' %}
									Income
								{% else %}
									Expense
								{% endif %}

							</td>
							<td class="px-6 py-3">{{ transaction.amount }}</td>
						</tr>

					{% endfor %}
						
				</tbody>
			</table>

		{% else %}

			<p class="text-2xl text-white">
				No transaction found!
			</p>

		{% endif %}
	</div>
	<!-- 1/4 of cols for filter form -->
	<div class="col-span-1">
		<form 
			hx-get="{% url 'finance:transactions_list' %}" 
			hx-target="#transaction_container" 
			hx-swap="outerHTML"
		>
			<div class="mb-2 form-control">

				{{ transaction_filter.form.transaction_type|add_label_class:"label text-white" }}
				{% render_field transaction_filter.form.transaction_type class="select bg-gray-50 text-gray-900" %}
				
			</div>
			<button class="btn btn-success">Filter</button>
		</form>
	</div>
</div>

finance/templates/finance/transactions_list.html
{% extends 'finance/base.html' %}

{% block head_title %}
	Transactions List
{% endblock head_title %}


{% block content %}

	<h1 class="mt-4 mb-4 text-2xl leading-none tracking-tight text-white md:text-3xl lg:text-4xl flex items-center">
		<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 me-2">
			<path stroke-linecap="round" stroke-linejoin="round" d="M8.25 6.75h12M8.25 12h12m-12 5.25h12M3.75 6.75h.007v.008H3.75V6.75Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0ZM3.75 12h.007v.008H3.75V12Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm-.375 5.25h.007v.008H3.75v-.008Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
		</svg>
		  
		Transactions List
	</h1>

	<div class="relative overflow-x-auto text-white">

		{% include 'finance/partials/transactions_container.html' %}
		
	</div>
	
{% endblock content %}
	
	